Problem Statement:
Given a N*N board with the Knight placed on the first block of an empty board. Moving according to the rules of chess knight must visit each square exactly once. Print the order of each the cell in which they are visited.

Attention reader! Don’t stop learning now. Get hold of all the important DSA concepts with the DSA Self Paced Course at a student-friendly price and become industry ready.  To complete your preparation from learning a language to DS Algo and many more,  please refer Complete Interview Preparation Course.

In case you wish to attend live classes with experts, please refer DSA Live Classes for Working Professionals and Competitive Programming Live for Students.

Example:


```
Input : 
N = 8
Output:
0  59  38  33  30  17   8  63
37  34  31  60   9  62  29  16
58   1  36  39  32  27  18   7
35  48  41  26  61  10  15  28
42  57   2  49  40  23   6  19
47  50  45  54  25  20  11  14
56  43  52   3  22  13  24   5
51  46  55  44  53   4  21  12
```

In [1]:
test_set = set([1, 67, 2, 3, 5])
test_set

{1, 2, 3, 5, 67}

In [2]:
test_set.add(3)

In [3]:
import numpy as np 
from typing import Tuple
import random 

class Knight:
    MOVES = [(2, 1), (1, 2), (-1, 2), (-2, 1), (-2, -1), (-1, -2), (1, -2), (2, -1)]
            #[(2, 1), (1, 2), (-1, 2), (-2, 1), (-2, -1), (-1, -2), (1, -2), (2, -1)]

    def __init__(self, N=8, pos=(0,0)):
        self._board = np.ones((N,N), np.int) * -1
        self._board[pos[0], pos[1]] = 0 # starting position

        self._longest_time = 1
    
    def is_valid(self, future_pos):
        shp = self._board.shape    
        try:
            return  future_pos is not None and \
                    future_pos[0] < shp[0] and future_pos[1] < shp[1]  and \
                    future_pos[0] >= 0     and future_pos[1] >= 0      and \
                    self._board[future_pos[0], future_pos[1]] == -1
        except:
            print(shp, future_pos)
            raise Exception
    
    def mark_seen(self, pos:Tuple[int,int], time):
        self._pos = pos
        self._board[pos[0], pos[1]] = time

        if time >= self._longest_time:
            self._longest_time = time
            print(f"Pos {self._pos} at time {time}")
            print(self._board)
    
    def undo_move(self, pos):
        self._board[pos[0], pos[1]] = -1
    

    def solve_all_cells(self, pos=(0,0), time=1):
        if time == self._board.size:
            return True
        
        for x,y in Knight.MOVES:
            future_pos = (pos[0] + x, pos[1] + y)
            if self.is_valid(future_pos):
                
                self.mark_seen(future_pos, time)
                
                if self.solve_all_cells(future_pos, time+1):
                    return True
                
                self.undo_move(future_pos)
            
        return False
      
    def solve_all_cells_simpler(self, board, pos=(0,0), time=1):
        
        if time == board.size:
            return True
        
        for x,y in Knight.MOVES:
            future_pos = (pos[0] + x, pos[1] + y)
            if self.is_valid(future_pos):
                
                board[future_pos[0], future_pos[1]] = time
                
                if self.solve_all_cells_2(board, future_pos, time+1):
                    return True
                
                board[future_pos[0], future_pos[1]] = -1
                
        return False
    
    @staticmethod
    def random_move():
        return random.choice(Knight.MOVES)

In [4]:
knight  = Knight(8)
board = knight._board
knight.solve_all_cells()

Pos (2, 1) at time 1
[[ 0 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1  1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]]
Pos (4, 2) at time 2
[[ 0 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1  1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1  2 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]]
Pos (6, 3) at time 3
[[ 0 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1  1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1  2 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1  3 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]]
Pos (7, 5) at time 4
[[ 0 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1  1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1  2 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1  3 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1  4 -1 -1]]
Pos (6, 7) at time 5
[[ 0 -1 -1 -1 -1 -1 -1 -1]


Pos (4, 0) at time 58
[[ 0 49 -1 33 30 17  8 -1]
 [51 -1 31 38  9 34 29 16]
 [48  1 50 35 32 27 18  7]
 [-1 52 37 26 39 10 15 28]
 [58 47  2 43 36 23  6 19]
 [53 44 55 40 25 20 11 14]
 [46 57 42  3 22 13 24  5]
 [-1 54 45 56 41  4 21 12]]
Pos (7, 3) at time 58
[[ 0 49 -1 33 30 17  8 -1]
 [51 -1 31 38  9 34 29 16]
 [48  1 50 35 32 27 18  7]
 [-1 52 37 26 39 10 15 28]
 [56 47  2 43 36 23  6 19]
 [53 44 55 40 25 20 11 14]
 [46 57 42  3 22 13 24  5]
 [-1 54 45 58 41  4 21 12]]
Pos (4, 0) at time 58
[[ 0 49 -1 33 30 17  8 -1]
 [-1 -1 31 38  9 34 29 16]
 [48  1 50 35 32 27 18  7]
 [-1 52 37 26 39 10 15 28]
 [58 47  2 51 36 23  6 19]
 [53 44 55 40 25 20 11 14]
 [46 57 42  3 22 13 24  5]
 [43 54 45 56 41  4 21 12]]
Pos (7, 3) at time 58
[[ 0 49 -1 33 30 17  8 -1]
 [-1 -1 31 38  9 34 29 16]
 [48  1 50 35 32 27 18  7]
 [-1 52 37 26 39 10 15 28]
 [56 47  2 51 36 23  6 19]
 [53 44 55 40 25 20 11 14]
 [46 57 42  3 22 13 24  5]
 [43 54 45 58 41  4 21 12]]
Pos (4, 0) at time 58
[[ 0 49 -1 33 30 17  8

[[ 0 39 58 33 30 17  8 -1]
 [57 -1 31 38  9 34 29 16]
 [40  1 46 35 32 27 18  7]
 [45 56 37 26 47 10 15 28]
 [50 41  2 55 36 23  6 19]
 [53 44 51 48 25 20 11 14]
 [42 49 54  3 22 13 24  5]
 [-1 52 43 -1 -1  4 21 12]]
Pos (4, 0) at time 58
[[ 0 39 -1 33 30 17  8 -1]
 [-1 -1 31 38  9 34 29 16]
 [40  1 50 35 32 27 18  7]
 [-1 52 37 26 49 10 15 28]
 [58 41  2 51 36 23  6 19]
 [53 44 55 48 25 20 11 14]
 [42 57 46  3 22 13 24  5]
 [45 54 43 56 47  4 21 12]]
Pos (7, 3) at time 58
[[ 0 39 -1 33 30 17  8 -1]
 [-1 -1 31 38  9 34 29 16]
 [40  1 50 35 32 27 18  7]
 [-1 52 37 26 49 10 15 28]
 [56 41  2 51 36 23  6 19]
 [53 44 55 48 25 20 11 14]
 [42 57 46  3 22 13 24  5]
 [45 54 43 58 47  4 21 12]]
Pos (4, 0) at time 58
[[ 0 39 -1 33 30 17  8 -1]
 [51 -1 31 38  9 34 29 16]
 [40  1 50 35 32 27 18  7]
 [-1 52 37 26 49 10 15 28]
 [58 41  2 -1 36 23  6 19]
 [53 44 55 48 25 20 11 14]
 [42 57 46  3 22 13 24  5]
 [45 54 43 56 47  4 21 12]]
Pos (7, 3) at time 58
[[ 0 39 -1 33 30 17  8 -1]
 [51 -1 31 38  9 

Pos (0, 2) at time 60
[[ 0 53 60 33 30 17  8 -1]
 [59 38 31 54  9 34 29 16]
 [52  1 56 35 32 27 18  7]
 [39 58 37 26 55 10 15 28]
 [-1 51  2 57 36 23  6 19]
 [43 40 45 48 25 20 11 14]
 [50 47 42  3 22 13 24  5]
 [41 44 49 46 -1  4 21 12]]
Pos (0, 2) at time 60
[[ 0 53 60 33 30 17  8 -1]
 [59 38 31 54  9 34 29 16]
 [52  1 56 35 32 27 18  7]
 [39 58 37 26 55 10 15 28]
 [46 51  2 57 36 23  6 19]
 [43 40 45 48 25 20 11 14]
 [50 47 42  3 22 13 24  5]
 [41 44 49 -1 -1  4 21 12]]
Pos (0, 2) at time 60
[[ 0 49 60 33 30 17  8 -1]
 [59 38 31 50  9 34 29 16]
 [48  1 40 35 32 27 18  7]
 [39 58 37 26 51 10 15 28]
 [-1 47  2 41 36 23  6 19]
 [57 44 55 52 25 20 11 14]
 [46 53 42  3 22 13 24  5]
 [43 56 45 54 -1  4 21 12]]
Pos (0, 2) at time 60
[[ 0 49 60 33 30 17  8 -1]
 [59 38 31 50  9 34 29 16]
 [48  1 40 35 32 27 18  7]
 [39 58 37 26 51 10 15 28]
 [54 47  2 41 36 23  6 19]
 [57 44 55 52 25 20 11 14]
 [46 53 42  3 22 13 24  5]
 [43 56 45 -1 -1  4 21 12]]
Pos (4, 0) at time 60
[[ 0 43 -1 33 30 17  8

Pos (7, 3) at time 60
[[ 0 45 -1 33 30 17  8 -1]
 [53 56 31 44  9 34 29 16]
 [46  1 54 35 32 27 18  7]
 [55 52 57 26 43 10 15 28]
 [58 47  2 51 36 23  6 19]
 [39 50 37 42 25 20 11 14]
 [48 59 40  3 22 13 24  5]
 [-1 38 49 60 41  4 21 12]]
Pos (0, 2) at time 60
[[ 0 53 60 33 30 17  8 -1]
 [59 46 31 54  9 34 29 16]
 [52  1 56 35 32 27 18  7]
 [47 58 45 26 55 10 15 28]
 [44 51  2 57 36 23  6 19]
 [39 48 37 42 25 20 11 14]
 [50 43 40  3 22 13 24  5]
 [-1 38 49 -1 41  4 21 12]]
Pos (0, 2) at time 60
[[ 0 51 60 33 30 17  8 -1]
 [59 46 31 50  9 34 29 16]
 [52  1 48 35 32 27 18  7]
 [47 58 45 26 49 10 15 28]
 [44 53  2 57 36 23  6 19]
 [39 56 37 42 25 20 11 14]
 [54 43 40  3 22 13 24  5]
 [-1 38 55 -1 41  4 21 12]]
Pos (7, 3) at time 60
[[ 0 47 -1 33 30 17  8 -1]
 [51 56 31 48  9 34 29 16]
 [46  1 50 35 32 27 18  7]
 [55 52 57 26 49 10 15 28]
 [58 45  2 53 36 23  6 19]
 [39 54 37 42 25 20 11 14]
 [44 59 40  3 22 13 24  5]
 [-1 38 43 60 41  4 21 12]]
Pos (0, 2) at time 60
[[ 0 47 60 33 30 17  8

Pos (7, 0) at time 61
[[ 0 55 36 33 30 17  8 -1]
 [37 48 31 56  9 34 29 16]
 [54  1 38 35 32 27 18  7]
 [49 40 47 26 57 10 15 28]
 [46 53  2 39 -1 23  6 19]
 [41 50 43 58 25 20 11 14]
 [52 45 60  3 22 13 24  5]
 [61 42 51 44 59  4 21 12]]
Pos (7, 2) at time 61
[[ 0 57 36 33 30 17  8 -1]
 [37 48 31 56  9 34 29 16]
 [58  1 38 35 32 27 18  7]
 [49 40 47 26 55 10 15 28]
 [46 59  2 39 -1 23  6 19]
 [41 50 43 54 25 20 11 14]
 [60 45 52  3 22 13 24  5]
 [51 42 61 44 53  4 21 12]]
Pos (3, 4) at time 61
[[ 0 59 36 33 30 17  8 -1]
 [37 48 31 60  9 34 29 16]
 [58  1 38 35 32 27 18  7]
 [49 40 47 26 61 10 15 28]
 [46 57  2 39 -1 23  6 19]
 [41 50 43 54 25 20 11 14]
 [56 45 52  3 22 13 24  5]
 [51 42 55 44 53  4 21 12]]
Pos (7, 0) at time 61
[[ 0 41 36 33 30 17  8 -1]
 [37 58 31 40  9 34 29 16]
 [42  1 38 35 32 27 18  7]
 [59 50 57 26 39 10 15 28]
 [56 43  2 49 -1 23  6 19]
 [51 60 53 46 25 20 11 14]
 [44 55 48  3 22 13 24  5]
 [61 52 45 54 47  4 21 12]]
Pos (3, 0) at time 61
[[ 0 41 36 33 30 17  8

Pos (0, 2) at time 62
[[ 0 45 62 33 30 17  8 -1]
 [61 34 31 46  9 48 29 16]
 [44  1 60 49 32 27 18  7]
 [35 58 51 26 47 10 15 28]
 [52 43  2 59 50 23  6 19]
 [57 36 55 40 25 20 11 14]
 [42 53 38  3 22 13 24  5]
 [37 56 41 54 39  4 21 12]]
Pos (4, 4) at time 62
[[ 0 45 50 33 30 17  8 -1]
 [51 34 31 46  9 48 29 16]
 [44  1 52 49 32 27 18  7]
 [35 54 61 26 47 10 15 28]
 [60 43  2 53 62 23  6 19]
 [55 36 57 40 25 20 11 14]
 [42 59 38  3 22 13 24  5]
 [37 56 41 58 39  4 21 12]]
Pos (7, 3) at time 62
[[ 0 45 50 33 30 17  8 -1]
 [51 34 31 46  9 48 29 16]
 [44  1 52 49 32 27 18  7]
 [35 54 59 26 47 10 15 28]
 [60 43  2 53 58 23  6 19]
 [55 36 57 40 25 20 11 14]
 [42 61 38  3 22 13 24  5]
 [37 56 41 62 39  4 21 12]]
Pos (0, 2) at time 62
[[ 0 47 62 33 30 17  8 -1]
 [61 34 31 48  9 50 29 16]
 [46  1 36 51 32 27 18  7]
 [35 60 53 26 49 10 15 28]
 [54 45  2 37 52 23  6 19]
 [59 38 57 42 25 20 11 14]
 [44 55 40  3 22 13 24  5]
 [39 58 43 56 41  4 21 12]]
Pos (4, 4) at time 62
[[ 0 47 52 33 30 17  8

True

```
0  59  38  33  30  17   8  63
37  34  31  60   9  62  29  16
58   1  36  39  32  27  18   7
35  48  41  26  61  10  15  28
42  57   2  49  40  23   6  19
47  50  45  54  25  20  11  14
56  43  52   3  22  13  24   5
51  46  55  44  53   4  21  12
```